=== kapodamy/kdmy-engine/docs/AnimationList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- For writting anims's xml files -->
    <!-- TODO: add assertions -->

    <xs:simpleType name="Interpolator-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="linear" />
            <xs:enumeration value="ease" />
            <xs:enumeration value="ease-in" />
            <xs:enumeration value="ease-out" />
            <xs:enumeration value="ease-in-out" />
            <xs:enumeration value="steps" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Interpolator-stepsMethod">
        <xs:restriction base="xs:string">
            <xs:enumeration value="start" />
            <xs:enumeration value="end" />
            <xs:enumeration value="both" />
            <xs:enumeration value="none" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="register">
        <xs:restriction base="xs:string">
            <xs:enumeration value="reg0" />
            <xs:enumeration value="reg1" />
            <xs:enumeration value="reg2" />
            <xs:enumeration value="reg3" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="percentDuration">
        <xs:restriction base="xs:string">
            <xs:pattern value="^\d+(\.\d+)?%?$" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Interpolator">
        <xs:attribute name="id" type="xs:anySimpleType" use="optional" default="-1" />
        <xs:attribute name="type" type="Interpolator-type" use="optional" default="linear" />
        <xs:attribute name="start" type="xs:anySimpleType" use="optional" default="0" />
        <xs:attribute name="end" type="xs:anySimpleType" use="optional" default="0" />
        <xs:attribute name="duration" type="xs:float" use="optional" default="-1" />
        <xs:attribute name="stepsCount" type="xs:integer" use="optional" default="-1" />
        <xs:attribute name="stepsMethod" type="Interpolator-stepsMethod" use="optional" default="start" />
    </xs:complexType>
    <xs:complexType name="FrameArray">
        <xs:attribute name="entryPrefixName" type="xs:string" use="optional" />
        <xs:attribute name="entrySuffixName" type="xs:string" use="optional" />
        <xs:attribute name="hasNumberSuffix" type="xs:boolean" use="optional" default="true" />
        <xs:attribute name="indexStart" type="xs:integer" use="optional" default="0" />
        <xs:attribute name="indexEnd" type="xs:integer" use="optional" default="-1" />
    </xs:complexType>
    <xs:complexType name="Frame">
        <xs:attribute name="entryName" type="xs:string" use="optional" />
    </xs:complexType>
    <xs:complexType name="Pause">
        <xs:attribute name="duration" type="xs:positiveInteger" use="optional" default="1" />
    </xs:complexType>
    <xs:complexType name="Set">
        <xs:attribute name="property" type="xs:string" use="optional" default="1" />
        <xs:attribute name="value" type="xs:anySimpleType" use="optional" default="1" />
    </xs:complexType>
    <xs:complexType name="Yield">
        <xs:attribute name="duration" type="xs:integer" use="optional" default="0" />
    </xs:complexType>
    <xs:complexType name="RandomSetup">
        <xs:attribute name="start" type="xs:float" use="optional" default="NaN" />
        <xs:attribute name="end" type="xs:float" use="optional" default="NaN" />
    </xs:complexType>
    <xs:complexType name="RandomExact">
        <xs:attribute name="values" type="xs:anySimpleType" use="required" />
    </xs:complexType>
    <xs:complexType name="RegisterProp">
        <xs:attribute name="register" type="register" use="required" />
        <xs:attribute name="property" type="xs:string" use="required" />
    </xs:complexType>
    <xs:complexType name="RegisterSet">
        <xs:attribute name="register" type="register" use="optional" />
        <xs:attribute name="value" type="xs:anySimpleType" use="optional" />
    </xs:complexType>
    <xs:complexType name="Keyframe">
        <xs:attribute name="at" type="percentDuration" use="required" />
        <xs:attribute name="id" type="xs:integer" use="optional" />
        <xs:attribute name="value" type="xs:double" use="required" />
        <xs:attribute name="interpolator" type="Interpolator-type" use="optional" />
        <xs:attribute name="stepMethods" type="Interpolator-stepsMethod" use="optional" default="none" />
        <xs:attribute name="stepCount" type="xs:positiveInteger" use="optional" />
    </xs:complexType>


    <xs:complexType name="Animation">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="FrameArray" type="FrameArray" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Frame" type="Frame" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Pause" type="Pause" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="AlternateSet" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="loop" type="xs:integer" default="1" use="optional" />
        <xs:attribute name="frameRate" type="xs:float" default="24" use="optional" />
        <xs:attribute name="alternateInLoops" type="xs:boolean" default="0" use="optional" />
        <xs:attribute name="alternateRandomize" type="xs:boolean" default="0" use="optional" />
        <xs:attribute name="atlasPath" type="xs:anyURI" use="optional" />
    </xs:complexType>
    <xs:complexType name="AnimationMacro">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="Interpolator" type="Interpolator" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Set" type="Set" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Yield" type="Yield" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Pause" type="Pause" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Reset" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="RandomSetup" type="RandomSetup" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="RandomChoose" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="RegisterProp" type="RegisterProp" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="RegisterSet" type="RegisterSet" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="loop" type="xs:integer" default="1" use="optional" />
        <xs:attribute name="frameRestartIndex" type="xs:integer" default="-1" use="optional" />
        <xs:attribute name="frameAllowChangeSize" type="xs:boolean" default="false" use="optional" />
        <xs:attribute name="atlasPath" type="xs:anyURI" use="optional" />
    </xs:complexType>
    <xs:complexType name="TweenKeyframe">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="Keyframe" type="Keyframe" minOccurs="1" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="defaultInterpolator" type="Interpolator-type" use="optional" default="linear" />
        <xs:attribute name="referenceDuration" type="xs:positiveInteger" use="optional" default="1" />
    </xs:complexType>


    <xs:element name="AnimationList">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="Animation" type="Animation" />
                <xs:element name="AnimationMacro" type="AnimationMacro" />
                <xs:element name="TweenKeyframe" type="TweenKeyframe" />
            </xs:sequence>
            <xs:attribute name="atlasPath" type="xs:anyURI" use="optional" />
        </xs:complexType>
    </xs:element>

</xs:schema>

=== kapodamy/kdmy-engine/assets/weeks/week7/kickstarter/anims.xml
<?xml version="1.0" encoding="utf-8"?>
<AnimationList
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../../../docs/AnimationList.xsd">

    <AnimationMacro name="video_fade_in_anim">
        <Interpolator property="alpha" duration="250" type="expo" start="0.0" end="1.0" />
    </AnimationMacro>
    <AnimationMacro name="video_fade_out_anim">
        <Interpolator property="alpha" duration="250" type="expo" start="1.0" end="0.0" />
    </AnimationMacro>  
    <AnimationMacro name="screen_fade_out_anim">
        <Interpolator property="alpha" duration="500" type="ease-out" start="0.0" end="1.0" />
    </AnimationMacro>

    <AnimationMacro name="selected_anim_left">
        <Interpolator property="skewX" duration="50" type="linear" start="-0.25" end="0" />
    </AnimationMacro>
    <AnimationMacro name="selected_anim_right">
        <Interpolator property="skewX" duration="50" type="linear" start="0.25" end="0" />
    </AnimationMacro>

</AnimationList>

=== kapodamy/kdmy-engine/assets/weeks/week7/tank_anims.xml
<?xml version="1.0" encoding="utf-8"?>
<AnimationList
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../../docs/AnimationList.xsd">

    <AnimationMacro name="video_fade_in_anim">
        <Interpolator property="alpha" duration="500" type="linear" start="0.0" end="1.0" />
    </AnimationMacro>

    <AnimationMacro name="bounce_fade_anim">
        <Interpolator property="alpha" duration="250" type="ease-in" start="0.0" end="1.0" />
        <Yield />
        <Interpolator property="alpha" duration="250" type="ease-out" end="0.0" />
    </AnimationMacro>

    <AnimationMacro name="fade_out_anim">
        <Interpolator property="alpha" duration="500" type="ease-out" start="0.0" end="1.0" />
    </AnimationMacro>

    <AnimationMacro name="tankClouds_locate_with_velocity">
        <!-- tankSky.x = FlxG.random.int(-700, -100) -->
        <RandomSetup start="-700" end="-100" />
        <RandomChoose />
        <Set property="x" value="rnd" />

        <!-- tankSky.y = FlxG.random.int(-20, 20) -->
        <RandomSetup start="-20" end="20" />
        <RandomChoose />
        <Set property="y" value="rnd" />

        <!-- tankSky.velocity.x = FlxG.random.float(5, 15); -->
        <!-- Note: there no velocity here only absolute units, use instead the total distance needed for 2m30s -->
        <RandomSetup start="750" end="2250" />
        <RandomChoose />
        <Interpolator property="translateX" duration="150000" type="linear" start="0" end="rnd" />
    </AnimationMacro>

</AnimationList>
