=== kapodamy/kdmy-engine/docs/character.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Character",
    "definitions": {
        "Character": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "healthbarColor": {
                    "type": ["integer", "string", "null"],
                    "default": "0x0000FF",
                    "description": "8bit RGB Color in format 0xRRGGBB"
                },
                "model": {
                    "type": "string"
                },
                "healthIconsModel": {
                    "type": ["string", "null"],
                    "default": null
                },
                "modelWeekSelector": {
                    "type": "string"
                },
                "singSuffix": {
                    "type": ["string", "null"],
                    "default": null
                },
                "singAlternateSuffix": {
                    "type": ["string", "null"],
                    "default": null
                },
                "continuousIdle": {
                    "type": "boolean",
                    "default": false
                },
                "actionsApplyChartSpeed": {
                    "type": "boolean",
                    "default": false
                },
                "offsetX": {
                    "type": "number",
                    "default": 0.0
                },
                "offsetY": {
                    "type": "number",
                    "default": 0.0
                },
                "leftFacing": {
                    "type": "boolean",
                    "default": false
                },
                "weekSelectorEnableBeat": {
                    "type": "boolean",
                    "default": true
                },
                "oppositeDirections": {
                    "$ref": "#/definitions/OppositeDirections"
                },
                "alignVertical": {
                    "type": "string",
                    "enum": ["start", "center", "end"],
                    "default": "center"
                },
                "alignHorizontal": {
                    "type": "string",
                    "enum": ["start", "center", "end"],
                    "default": "center"
                },
                "referenceSize": {
                    "$ref": "#/definitions/ReferenceSize"
                },
                "singPrefix": {
                    "type": ["string", "null"],
                    "default": null
                },
                "singAlternatePrefix": {
                    "type": ["string", "null"],
                    "default": null
                },
                "allowAlternateIdle": {
                    "type": "boolean",
                    "default": false
                },
                "actions": {
                    "$ref": "#/definitions/Actions"
                },
                "additionalStates": {
                    "type": ["null", "array"],
                    "items": {
                        "$ref": "#/definitions/AdditionalState"
                    }
                }
            },
            "required": [
                "healthIconsModel",
                "healthbarColor"
            ],
            "title": "Character manifest"
        },
        "Actions": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "sing": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Sing"
                    }
                },
                "miss": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Miss"
                    }
                },
                "idle": {
                    "$ref": "#/definitions/Extra"
                },
                "hey": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Extra"
                    }
                },
                "extras": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Extra"
                    }
                }
            }
        },
        "Extra": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "anim": {
                    "type": ["string", "null"],
                    "default": null
                },
                "animHold": {
                    "type": ["string", "null"],
                    "default": null
                },
                "animRollback": {
                    "type": ["string", "null"],
                    "default": null
                },
                "stopAfterBeats": {
                    "type": "integer",
                    "default": -1
                },
                "staticUntilBeat": {
                    "type": "boolean",
                    "default": true
                },
                "model": {
                    "type": ["string", "null"],
                    "default": null
                },
                "offsetX": {
                    "type": "number",
                    "default": 0.0
                },
                "offsetY": {
                    "type": "number",
                    "default": 0.0
                }
            },
            "title": "Extra"
        },
        "Miss": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "direction": {
                    "type": "string"
                },
                "anim": {
                    "type": ["string", "null"],
                    "default": null
                },
                "stopAfterBeats": {
                    "type": "integer",
                    "default": -1
                },
                "model": {
                    "type": ["string", "null"],
                    "default": null
                },
                "offsetX": {
                    "type": "number",
                    "default": 0.0
                },
                "offsetY": {
                    "type": "number",
                    "default": 0.0
                }
            },
            "required": [
                "anim",
                "direction"
            ],
            "title": "Miss"
        },
        "OppositeDirections": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "from": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "to": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "from",
                "to"
            ],
            "title": "OppositeDirections"
        },
        "ReferenceSize": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "width": {
                    "type": "number"
                },
                "height": {
                    "type": "number"
                }
            },
            "required": [
                "height",
                "width"
            ],
            "title": "ReferenceSize"
        },
        "Sing": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "direction": {
                    "type": "string"
                },
                "anim": {
                    "type": "string"
                },
                "animHold": {
                    "type": ["string", "null"],
                    "default": null
                },
                "animRollback": {
                    "type": ["string", "null"],
                    "default": null
                },
                "rollback": {
                    "type": "boolean",
                    "default": false
                },
                "followHold": {
                    "type": "boolean",
                    "default": false
                },
                "fullSustain": {
                    "type": "boolean",
                    "default": false
                },
                "model": {
                    "type": ["string", "null"],
                    "default": null
                },
                "offsetX": {
                    "type": "number",
                    "default": 0.0
                },
                "offsetY": {
                    "type": "number",
                    "default": 0.0
                }
            },
            "required": [
                "anim",
                "direction"
            ],
            "title": "Sing"
        },
        "AdditionalState": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "model": {
                    "type": ["string", "null"],
                    "default": null
                },
                "actions":{
                    "$ref": "#/definitions/Actions"
                }
            },
            "required": [
                "name",
                "actions"
            ]
        }
    }
}

=== kapodamy/kdmy-engine/assets/weeks/week4/MM/MOMMY_MEAREST.json
{
    "model": "momCar.xml",
    "healthbarColor": "0xD8558E",
	"healthIconsModel": "icon-mom.xml",

    "alignVertical": "end",
    "alignHorizontal": "start",
    "leftFacing": false,
    "continuousIdle": true,

    "actions": {

        "sing": [
            { "direction": "left",   "anim": "Mom Left Pose",   "offsetX": -74  },
            { "direction": "down",   "anim": "MOM DOWN POSE"                    },
            { "direction": "up",     "anim": "Mom Up Pose",     "offsetX": 18   },
            { "direction": "right",  "anim": "Mom Right Pose"                   }
        ],

        "idle": { "anim": "Mom Idle" }
    }
}

=== kapodamy/kdmy-engine/assets/weeks/week6/funkin/BOYFRIEND_PIXEL.json
{
    "model": "bfPixel.xml",
    "healthbarColor": "0x31B3D1",
    "healthIconsModel": "icon-bf-pixel.xml",
    
	"alignVertical": "end",
    "alignHorizontal": "start",
    "leftFacing": true,

    "actions": {

        "sing": [
            { "direction": "left",   "anim": "BF LEFT NOTE instance"  },
            { "direction": "down",   "anim": "BF DOWN NOTE instance"  },
            { "direction": "up",     "anim": "BF UP NOTE instance"    },
            { "direction": "right",  "anim": "BF RIGHT MISS instance" }
        ],

        "miss": [
            { "direction": "left",   "anim": "BF LEFT MISS instance" },
            { "direction": "down",   "anim": "BF DOWN MISS instance" },
            { "direction": "up",     "anim": "BF UP MISS instance"   },
            { "direction": "right",  "anim": "BF RIGHT MISS instance" }
        ],

        "idle": { "anim": "BF IDLE instance" },
		
		"extras": [
            { "name": "dies",        "anim": "BF Dies pixel",   "animHold": "Retry Loop", 	"model": "bfPixelsDEAD.xml" },
            { "name": "retry",       "anim": "RETRY CONFIRM",   "animHold": null, 			"model": "bfPixelsDEAD.xml" },
            { "name": "giveup",      "anim": "Retry Loop",      "animHold": null, 			"model": "bfPixelsDEAD.xml" }
		]
    }
}

=== kapodamy/kdmy-engine/assets/weeks/week6/funkin/SPIRIT.json
{
    "model": "spirit.txt",
    "healthbarColor": "0xFF3C6E",
    "healthIconsModel": "icon-spirit.xml",

    "alignVertical": "end",
    "alignHorizontal": "start",
    "leftFacing": false, 
    "oppositeDirections": {
        "from": ["left", "right"],
        "to": ["right", "left"]
    },

    "actions": {

        "sing": [
            { "direction": "left",   "anim": "left_"  },
            { "direction": "down",   "anim": "spirit down_", "offsetX": -65, "offsetY": 65 },
            { "direction": "up",     "anim": "up_"    },
            { "direction": "right",  "anim": "right_" }
        ],
        
		"idle": { "anim": "idle spirit_" }
    }
}

=== kapodamy/kdmy-engine/assets/weeks/week6/funkin/SENPAI.json
{
    "model": "senpai.xml",
    "healthbarColor": "0xFFAA6F",
    "healthIconsModel": "icon-senpai.xml",

    "alignVertical": "end",
    "alignHorizontal": "start",
    "leftFacing": false, 

    "oppositeDirections": {
        "from": ["left", "right"],
        "to": ["right", "left"]
    },

    "actions": {

        "sing": [
            { "direction": "left",   "anim": "SENPAI LEFT NOTE instance"  },
            { "direction": "down",   "anim": "SENPAI DOWN NOTE instance"  },
            { "direction": "up",     "anim": "SENPAI UP NOTE instance"    },
            { "direction": "right",  "anim": "SENPAI RIGHT NOTE instance" }
        ],

        "idle": { "anim": "Senpai Idle instance" }
    }
}

=== kapodamy/kdmy-engine/assets/weeks/week6/funkin/SENPAI_ANGRY.json
{
    "model": "senpai.xml",
    "healthbarColor": "0xC05D68",
    "healthIconsModel": "icon-senpai.xml",

    "alignVertical": "end",
    "alignHorizontal": "start",
    "leftFacing": false, 

    "oppositeDirections": {
        "from": ["left", "right"],
        "to": ["right", "left"]
    },

    "actions": {

        "sing": [
            { "direction": "left",   "anim": "Angry Senpai LEFT NOTE instance"  },
            { "direction": "down",   "anim": "Angry Senpai DOWN NOTE instance"  },
            { "direction": "up",     "anim": "Angry Senpai UP NOTE instance"    },
            { "direction": "right",  "anim": "Angry Senpai RIGHT NOTE instance" }
        ],

        "idle": { "anim": "Angry Senpai Idle instance" }
    }
}

=== kapodamy/kdmy-engine/assets/weeks/week4/funkin/BOYFRIEND_CAR.json
{
    "model": "bfCar.xml",
    "healthbarColor": "0x31B3D1",
    "healthIconsModel": "/assets/common/image/funkin/icon-bf.xml",
    
	"alignVertical": "end",
    "alignHorizontal": "start",
    "leftFacing": true,

    "actions": {

        "sing": [
            { "direction": "left",   "anim": "BF NOTE LEFT"  },
            { "direction": "down",   "anim": "BF NOTE DOWN"  },
            { "direction": "up",     "anim": "BF NOTE UP"    },
            { "direction": "right",  "anim": "BF NOTE RIGHT" }
        ],

        "miss": [
            { "direction": "left",   "anim": "BF NOTE LEFT MISS"    },
            { "direction": "down",   "anim": "BF NOTE DOWN MISS"    },
            { "direction": "up",     "anim": "BF NOTE UP MISS"      },
            { "direction": "right",  "anim": "BF NOTE RIGHT MISS"   }
        ],

        "idle": { "animHold": "BF idle dance" },
		
		"extras": [
            { "name": "dies",        "anim": "BF dies",         "animHold": "BF Dead Loop", "model": "/assets/common/image/funkin/BOYFRIEND.xml" },
            { "name": "retry",       "anim": "BF Dead confirm",                             "model": "/assets/common/image/funkin/BOYFRIEND.xml" }
		]
    }
}

=== kapodamy/kdmy-engine/assets/weeks/week2/LMNDMN/LEMON_DEMON.json
{
    "model": "Monster_Assets.xml",
    "healthbarColor": "0xf3ff6e",
	"healthIconsModel": "icon-monster.xml",

    "alignVertical": "end",
    "alignHorizontal": "start",
    "leftFacing": false,

    "actions": {

        "sing": [
            { "direction": "left",   "anim": "Monster left note" },
            { "direction": "down",   "anim": "monster down" },
            { "direction": "up",     "anim": "monster up note" },
            { "direction": "right",  "anim": "Monster Right note" }
        ],

        "idle": { "anim": "monster idle" }
    }
}
