=== kapodamy/kdmy-engine/docs/expansion.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/About",
    "definitions": {
        "About": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": ["string", "null"],
                    "default": null
                },
                "version": {
                    "type": ["string", "null"],
                    "default": null
                },
                "submiter": {
                    "type": ["string", "null"],
                    "default": null
                },
                "description": {
                    "type": ["string", "null"],
                    "default": null
                },
                "screenshoot": {
                    "type": ["string", "null"],
                    "default": null
                },
                "icon": {
                    "type": ["string", "null"],
                    "default": null
                },
                "overrideWeeksFolder": {
                    "type": "boolean",
                    "default": false
                },
                "windowIcon": {
                    "type": ["string", "null"],
                    "default": null
                },
                "windowTitle": {
                    "type": ["string", "null"],
                    "default": null
                }
            },
            "title": "About (expansion descriptor)"           
        }
    }
}

=== kapodamy/kdmy-engine/expansions/example-expansion/expansion.json
{
    "name": "EXPANSION NAME GOES HERE",
    "version": "1.10.0-example",
    "submiter": "<insert-username>",
    "description": "Â¡hello world!\nthis is an example expansion",
    "screenshoot": "path/to/your/screenshot/image.png",
    "icon": "path/to/your/icon with a ideal size of 32x32.png",
    "overrideWeeksFolder": false
}
